### ISSUE TITLE
'.' should be escaped in regular expressions for hostnames

### ISSUE THREAD

**Issue by fnielsen** [citation-js/plugin-software-formats#12]
`predicate: /^https?:\/\/api.github.com\/repos\/[^/]+\//,` should probably be `predicate: /^https?:\/\/api\.github\.com\/repos\/[^/]+\//,`.

The same for ` predicate: /^https?:\/\/registry.npmjs.org\//,`

See https://github.com/WDscholia/scholia/pull/1939/files

**Comment by larsgw** [comment]
Thank you for the report. I released a fix in `v0.5.3` and I can create a PR to update Scholia.

**Comment by fnielsen** [comment]
Thanks for the PR!
